-- 1. Crear la tabla
create table public.evaluaciones_erge (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  email text,
  score integer,
  respuestas jsonb
);

-- 2. Habilitar Row Level Security (RLS)
alter table public.evaluaciones_erge enable row level security;

-- 3. Crear política para permitir inserciones públicas (necesario para la API anónima)
create policy "Enable insert for anon users only"
on public.evaluaciones_erge
for insert
to anon
with check (true);

-- 4. (Opcional) Política para permitir select si necesitas leer datos desde el frontend
-- create policy "Enable read access for all users"
-- on public.evaluaciones_erge
-- for select
-- using (true);
