import React from 'react';

export const BrainIcon: React.FC = () => <i className="fas fa-brain text-xl"></i>;
export const ArrowLeftIcon: React.FC = () => <i className="fas fa-arrow-left"></i>;
export const CompassIcon: React.FC = () => <i className="fas fa-compass text-indigo-500"></i>;
export const ListCheckIcon: React.FC = () => <i className="fas fa-list-check text-indigo-500"></i>;
export const StarOfLifeIcon: React.FC = () => <i className="fas fa-star-of-life text-indigo-500"></i>;
export const StethoscopeIcon: React.FC = () => <i className="fas fa-stethoscope text-indigo-500"></i>;
export const DiagramProjectIcon: React.FC = () => <i className="fas fa-diagram-project text-indigo-500"></i>;
export const ClipboardListIcon: React.FC = () => <i className="fas fa-clipboard-list text-indigo-500"></i>;
export const RankingStarIcon: React.FC = () => <i className="fas fa-ranking-star text-indigo-500"></i>;
export const BookOpenIcon: React.FC = () => <i className="fas fa-book-open text-indigo-500"></i>;
export const LightbulbIcon: React.FC = () => <i className="fas fa-lightbulb text-indigo-500"></i>;
export const ToolboxIcon: React.FC = () => <i className="fas fa-toolbox text-indigo-500"></i>;
export const ClockIcon: React.FC = () => <i className="fas fa-clock text-white/80"></i>;
export const UserMdIcon: React.FC = () => <i className="fas fa-user-md text-white/80"></i>;
export const TriangleExclamationIcon: React.FC = () => <i className="fas fa-triangle-exclamation text-amber-500 mt-1"></i>;
export const PuzzlePieceIcon: React.FC = () => <i className="fas fa-puzzle-piece text-indigo-500 mt-1"></i>;
export const UserClockIcon: React.FC = () => <i className="fas fa-user-clock text-cyan-500 mt-1"></i>;
export const PlusIcon: React.FC = () => <i className="fas fa-plus group-open:rotate-45 transition-transform"></i>;
export const NetworkWiredIcon: React.FC = () => <i className="fas fa-network-wired text-indigo-500"></i>;
export const ClipboardCheckIcon: React.FC = () => <i className="fas fa-clipboard-check text-indigo-500"></i>;
export const CommentsIcon: React.FC = () => <i className="fas fa-comments text-indigo-500"></i>;
export const VialIcon: React.FC = () => <i className="fas fa-vial text-indigo-500"></i>;
export const EyeIcon: React.FC = () => <i className="fas fa-eye text-indigo-500"></i>;
export const CameraIcon: React.FC = () => <i className="fas fa-camera text-indigo-500"></i>;
export const ArrowsToEyeIcon: React.FC = () => <i className="fas fa-arrows-to-eye text-indigo-500"></i>;
export const FaceSmileIcon: React.FC = () => <i className="fas fa-face-smile text-indigo-500"></i>;
export const NotesMedicalIcon: React.FC = () => <i className="fas fa-notes-medical"></i>;
export const StopwatchIcon: React.FC = () => <i className="fas fa-stopwatch"></i>;
export const BoltIcon: React.FC = () => <i className="fas fa-bolt text-amber-300 mt-1"></i>;
export const CircleNodesIcon: React.FC = () => <i className="fas fa-circle-nodes text-sky-300 mt-1"></i>;
export const PersonChalkboardIcon: React.FC = () => <i className="fas fa-person-chalkboard"></i>;
export const HandWaveIcon: React.FC = () => <i className="fas fa-hand-wave text-indigo-500"></i>;
export const RouteIcon: React.FC = () => <i className="fas fa-route"></i>;
export const GemIcon: React.FC = () => <i className="fas fa-gem"></i>;
export const FileDownloadIcon: React.FC = () => <i className="fas fa-file-download"></i>;
export const BellIcon: React.FC = () => <i className="fas fa-bell"></i>;
export const VideoIcon: React.FC = () => <i className="fas fa-video text-indigo-500"></i>;
export const BookIcon: React.FC = () => <i className="fas fa-book text-indigo-500"></i>;
export const LaptopMedicalIcon: React.FC = () => <i className="fas fa-laptop-medical text-indigo-500"></i>;
export const SquareIcon: React.FC = () => <i className="fas fa-square text-indigo-400 mt-1"></i>;
export const UserIcon: React.FC = () => <i className="fas fa-user text-indigo-500 mt-1"></i>;
export const FeatherIcon: React.FC = () => <i className="fas fa-feather text-sky-500 mt-1"></i>;
export const MinusIcon: React.FC = () => <i className="fas fa-minus text-sky-500 mt-1"></i>;
export const EyeDropperIcon: React.FC = () => <i className="fas fa-eye-dropper"></i>;
export const FlaskIcon: React.FC = () => <i className="fas fa-flask text-indigo-500 mt-1"></i>;
export const NoseIcon: React.FC = () => <i className="fas fa-nose"></i>;
export const PersonRaysIcon: React.FC = () => <i className="fas fa-person-rays"></i>;
export const FaceMehIcon: React.FC = () => <i className="fas fa-face-meh"></i>;